name: doctor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/League_Spartan/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Black.ttf
          weight: 900
        - asset: assets/fonts/League_Spartan/LeagueSpartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/League_Spartan/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Thin.ttf
          weight: 100
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100